In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,5,6+8j])

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+8.j])

In [8]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [15]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [17]:
np.array([[2,3],[4,5]])

array([[2, 3],
       [4, 5]])

In [29]:
arr=np.array([(1,2),(4,5)],dtype=[('a','<i2'),('b','<i8')])

In [22]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [25]:
type(arr[0][0])

numpy.int16

In [27]:
type(arr[0][1])

numpy.int64

In [30]:
arr = np.array([[2,3],[4,5]])

In [31]:
arr[1][0]

4

In [32]:
arr[0]

array([2, 3])

In [38]:
mat1= np.mat(arr)

In [34]:
l=[3,2,4,5,6,6]

In [35]:
np.array(l)

array([3, 2, 4, 5, 6, 6])

In [36]:
np.asarray(l)

array([3, 2, 4, 5, 6, 6])

In [39]:
np.asanyarray(mat1)

matrix([[2, 3],
        [4, 5]])

In [41]:
issubclass(np.ndarray,np.matrix)

False

In [42]:
a= arr

In [43]:
b=np.copy(arr)

In [44]:
arr[0][0]=67

In [45]:
a

array([[67,  3],
       [ 4,  5]])

In [46]:
b

array([[2, 3],
       [4, 5]])

In [51]:
arr[0:2]

array([[67,  3],
       [ 4,  5]])

In [52]:
for i in arr:
    print(i)

[67  3]
[4 5]


In [56]:
np.fromfunction(lambda i,j:i/j,(4,4))

C:\Users\KalpeshThakre\AppData\Local\Temp\ipykernel_17576\1565729657.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j:i/j,(4,4))
C:\Users\KalpeshThakre\AppData\Local\Temp\ipykernel_17576\1565729657.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j:i/j,(4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

In [69]:
gen = (i*i for i in range(5))

In [60]:
def test(x):
    yield x

In [61]:
test(5)

<generator object test at 0x0000021C53F4FAC0>

In [64]:
np.fromiter(gen,dtype =int)

array([ 0,  1,  4,  9, 16])

In [68]:
for i in gen:
    print(i)

In [70]:
np.fromstring('1,2,3,4,5',sep=',',dtype= int)

array([1, 2, 3, 4, 5])

In [71]:
l=[3,4,5,6,5,6,7,8,9]

In [73]:
arr =np.array(l)

In [78]:
arr1 =np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

In [75]:
type(arr)

numpy.ndarray

In [76]:
type(arr1)

list

In [79]:
arr1.ndim

2

In [80]:
arr1.size

12

In [81]:
arr1.shape

(3, 4)

In [82]:
arr.size

9

In [83]:
arr.ndim

1

In [84]:
arr.shape

(9,)

In [90]:
arr2= np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [91]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [92]:
arr2.size


32

In [94]:
arr2.shape

(4, 2, 4)

In [95]:
arr2.ndim

3

In [98]:
list(range(5))

[0, 1, 2, 3, 4]

In [107]:
np.arange(9,6.6,-.1)

array([9. , 8.9, 8.8, 8.7, 8.6, 8.5, 8.4, 8.3, 8.2, 8.1, 8. , 7.9, 7.8,
       7.7, 7.6, 7.5, 7.4, 7.3, 7.2, 7.1, 7. , 6.9, 6.8, 6.7, 6.6])

In [109]:
np.linspace(3,8,5)

array([3.  , 4.25, 5.5 , 6.75, 8.  ])

In [110]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [115]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [116]:
np.ones(4)

array([1., 1., 1., 1.])

In [118]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [120]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [122]:
np.empty((3,4))

array([[0.        , 0.        , 0.        , 1.        ],
       [0.5       , 0.33333333, 2.        , 1.        ],
       [0.66666667, 3.        , 1.5       , 1.        ]])

In [128]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [135]:
np.linspace([2,4],4,axis= 1)

array([[2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
        2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
        2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
        2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
        2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
        3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
        3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
        3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
        3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
        3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ],
       [4.        , 4.        , 4.        , 4.        , 4.        ,
        4.        , 4.        , 4.        , 4.        , 4.        ,
        4.        , 4.        , 4.        , 4.        , 4.        ,
        4.        , 4.        , 4.        , 4.        , 4.        ,
        4.        , 4.        , 4.        , 4. 

In [140]:
np.logspace([2],[3])

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [141]:
d = np.linspace(4,7,40)

In [142]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [143]:
d.ndim

1

In [144]:
d.shape

(40,)

In [145]:
d.T

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [147]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [149]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [150]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [156]:
np.random.randn(5)

array([ 0.61155283,  0.83800221, -1.02308176, -0.97076706,  0.82124209])

In [160]:
np.random.randint(3,33,(4,4))

array([[24, 11, 31, 26],
       [17, 26, 15, 29],
       [20, 11, 13, 13],
       [24, 17, 16, 11]])

In [161]:
arr = np.random.randint(3,9,(3,3))

In [162]:
arr

array([[5, 4, 8],
       [8, 7, 7],
       [8, 3, 6]])

In [163]:
arr.reshape(1,9)

array([[5, 4, 8, 8, 7, 7, 8, 3, 6]])

In [164]:
arr.reshape(9,1)

array([[5],
       [4],
       [8],
       [8],
       [7],
       [7],
       [8],
       [3],
       [6]])

In [165]:
arr.reshape(1,1,9)

array([[[5, 4, 8, 8, 7, 7, 8, 3, 6]]])

In [167]:
arr.reshape(3,-1)

array([[5, 4, 8],
       [8, 7, 7],
       [8, 3, 6]])

In [170]:
arr.reshape(9,-1334)

array([[5],
       [4],
       [8],
       [8],
       [7],
       [7],
       [8],
       [3],
       [6]])

In [171]:
arr.max()

8

In [174]:
arr = np.random.randint(4,100,(5,5))

In [181]:
arr

array([[30,  4, 10, 98, 38],
       [32, 58, 63, 82, 36],
       [53, 42, 47, 85, 53],
       [ 4, 90, 89, 41, 94],
       [16, 12, 77, 93, 88]])

In [182]:
arr[3:,3:]

array([[41, 94],
       [93, 88]])

In [184]:
arr[:,[1,3]]

array([[ 4, 98],
       [58, 82],
       [42, 85],
       [90, 41],
       [12, 93]])

In [185]:
arr[[2,3],:]

array([[53, 42, 47, 85, 53],
       [ 4, 90, 89, 41, 94]])

In [187]:
arr[arr>10]

array([30, 98, 38, 32, 58, 63, 82, 36, 53, 42, 47, 85, 53, 90, 89, 41, 94,
       16, 12, 77, 93, 88])

In [188]:
arr

array([[30,  4, 10, 98, 38],
       [32, 58, 63, 82, 36],
       [53, 42, 47, 85, 53],
       [ 4, 90, 89, 41, 94],
       [16, 12, 77, 93, 88]])

In [189]:
arr * arr

array([[ 900,   16,  100, 9604, 1444],
       [1024, 3364, 3969, 6724, 1296],
       [2809, 1764, 2209, 7225, 2809],
       [  16, 8100, 7921, 1681, 8836],
       [ 256,  144, 5929, 8649, 7744]])

In [190]:
arr1 = np.random.randint(2,4,(3,3))

In [192]:
arr2 = np.random.randint(2,4,(3,3))

In [193]:
arr1

array([[2, 3, 3],
       [2, 3, 2],
       [3, 2, 2]])

In [194]:
arr2

array([[2, 2, 3],
       [2, 3, 3],
       [2, 3, 2]])

In [195]:
arr1 * arr2

array([[4, 6, 9],
       [4, 9, 6],
       [6, 6, 4]])

In [196]:
arr1 * arr2

array([[4, 6, 9],
       [4, 9, 6],
       [6, 6, 4]])

In [197]:
arr1 @ arr2

array([[16, 22, 21],
       [14, 19, 19],
       [14, 18, 19]])

In [201]:
np.mat(arr1)* np.mat(arr2)

matrix([[16, 22, 21],
        [14, 19, 19],
        [14, 18, 19]])

In [205]:
arr = np.zeros((3,4))

In [206]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [215]:
a= np.array([1,2,3,4])

In [214]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [216]:
b=np.array([5,6,7])

In [217]:
b

array([5, 6, 7])

In [219]:
b.reshape(3,1)+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [229]:
np.random.seed(45)
np.random.rand(2,4)

array([[0.98901151, 0.54954473, 0.2814473 , 0.07728957],
       [0.4444695 , 0.47280797, 0.048522  , 0.16332445]])